"""Conversation service for saving user-bot interactions to database.

This module provides a simple service to save conversations to the database.
It handles errors gracefully and never crashes the application.

The service is designed to be called AFTER bot replies are generated and sent,
ensuring that message sending is never affected by database operations.
"""
import logging

from app.models import Conversation
from app.database import get_db_context
from app.services.ai_brain import detect_intent
from app.schemas import NormalizedMessage, MessageChannel

log = logging.getLogger(__name__)


async def save_conversation(
    user_message: str,
    bot_reply: str,
    channel: str,
    user_id: str,
    intent: str = None,
) -> bool:
    """
    Save a conversation to the database.

    This function saves user messages and bot replies along with metadata.
    It handles all errors gracefully and never raises exceptions.

    Args:
        user_message: The original message from the user
        bot_reply: The response generated by the AI brain
        channel: Messaging platform (telegram, whatsapp, instagram)
        user_id: Platform-specific user identifier
        intent: Detected intent (optional, will be detected if not provided)

    Returns:
        True if conversation saved successfully, False otherwise
    """
    try:
        # If intent not provided, detect it from user message
        if intent is None:
            try:
                # Create a temporary NormalizedMessage to detect intent
                from datetime import datetime
                temp_message = NormalizedMessage(
                    channel=MessageChannel.TELEGRAM,  # Default, not used for detection
                    user_id=user_id,
                    message_text=user_message,
                    timestamp=datetime.utcnow(),
                )
                detected_intent = detect_intent(temp_message)
                intent = detected_intent.value
                log.debug(f"intent_detected_for_save user_id={user_id} intent={intent}")
            except Exception as e:
                log.warning(f"intent_detection_failed_for_save user_id={user_id} error={type(e).__name__} action=using_unknown")
                intent = "unknown"

        # Validate required fields
        if not user_message or not bot_reply or not channel or not user_id:
            log.warning(f"conversation_save_validation_failed user_id={user_id} reason=missing_fields")
            return False

        # Save to database
        with get_db_context() as db:
            conversation = Conversation(
                user_id=user_id,
                channel=channel,
                user_message=user_message,
                bot_reply=bot_reply,
                intent=intent,
            )
            db.add(conversation)
            # get_db_context() automatically commits on success

        log.debug(f"conversation_saved user_id={user_id} channel={channel} intent={intent}")
        return True

    except Exception as e:
        # Log error but never crash
        log.error(
            f"conversation_save_error user_id={user_id} channel={channel} "
            f"error={type(e).__name__} message={str(e)}",
            exc_info=True
        )
        return False


async def save_conversation_from_normalized(
    normalized_message: NormalizedMessage,
    bot_reply: str,
    intent: str = None,
) -> bool:
    """
    Save a conversation from NormalizedMessage and bot reply.

    Convenience function that extracts data from NormalizedMessage
    and saves the conversation.

    Args:
        normalized_message: Normalized message from any platform
        bot_reply: The response generated by the AI brain
        intent: Detected intent (optional, will be detected if not provided)

    Returns:
        True if conversation saved successfully, False otherwise
    """
    try:
        return await save_conversation(
            user_message=normalized_message.message_text,
            bot_reply=bot_reply,
            channel=normalized_message.channel.value,
            user_id=normalized_message.user_id,
            intent=intent,
        )
    except Exception as e:
        log.error(f"Failed to save conversation from normalized message: {e}", exc_info=True)
        return False

