"""Database models using SQLAlchemy ORM.

This module contains all database models for the application.
Models inherit from Base (defined in database.py) and represent
database tables using SQLAlchemy's declarative syntax.

All models are designed for Supabase PostgreSQL.
"""
from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Float
from sqlalchemy.orm import relationship

from app.database import Base


class Conversation(Base):
    """
    Conversation model for storing user-bot interactions.

    This model stores complete conversation records including:
    - User messages and bot replies
    - Channel/platform information
    - Detected intent
    - Timestamp for each conversation
    - Business/workspace association (multi-tenant)

    Table: conversations
    """

    __tablename__ = "conversations"

    # Primary key - auto-incrementing integer
    id = Column(Integer, primary_key=True, index=True)

    # Business/Workspace - links conversation to a specific business (multi-tenant)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)

    # User identifier - platform-specific user ID (e.g., Telegram user ID)
    # Stored as string to support different platform ID formats
    user_id = Column(String, nullable=False, index=True)

    # Channel/platform - messaging platform (telegram, whatsapp, instagram)
    # Stored as string matching MessageChannel enum values
    channel = Column(String, nullable=False, index=True)

    # User message - the original message from the user
    # Using Text type to support long messages
    user_message = Column(Text, nullable=False)

    # Bot reply - the response generated by the AI brain
    # Using Text type to support long responses
    bot_reply = Column(Text, nullable=False)

    # Intent - detected intent from the message (greeting, help, pricing, etc.)
    # Stored as string matching Intent enum values from ai_brain.py
    intent = Column(String, nullable=False, index=True)

    # Created timestamp - when the conversation was recorded
    # Automatically set to current UTC time when record is created
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class User(Base):
    """
    User model for authentication and access control.

    Supports multiple roles: Admin, Business Owner, Agent
    Admin users don't need a business_id (platform-level access)
    Business owners and agents are linked to a business (multi-tenant)
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, nullable=False, default="agent")  # admin, business_owner, agent
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)  # Nullable for admin users
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Business(Base):
    """
    Business/Workspace model for multi-tenant support.
    """
    __tablename__ = "businesses"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    settings = Column(Text, nullable=True)  # JSON string for flexible settings
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ChannelIntegration(Base):
    """
    Channel integration model for managing platform connections.
    """
    __tablename__ = "channel_integrations"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)  # telegram, whatsapp, instagram, etc.
    channel_name = Column(String, nullable=True)  # Custom name for the integration
    credentials = Column(Text, nullable=True)  # Encrypted JSON credentials
    is_active = Column(Boolean, default=True, nullable=False)
    webhook_url = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Message(Base):
    """
    Individual message model for detailed conversation tracking.
    """
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)  # Multi-tenant support
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=True, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    message_text = Column(Text, nullable=False)
    is_from_user = Column(Boolean, nullable=False)  # True = user message, False = bot reply
    intent = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class Lead(Base):
    """
    Lead model for capturing and tracking potential customers.
    """
    __tablename__ = "leads"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True, index=True)
    phone = Column(String, nullable=True)
    status = Column(String, default="new", nullable=False, index=True)  # new, contacted, qualified, converted
    source_intent = Column(String, nullable=True)  # Intent that triggered lead capture
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class KnowledgeEntry(Base):
    """
    Knowledge base entry model for FAQs and documents.
    """
    __tablename__ = "knowledge_entries"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    keywords = Column(Text, nullable=True)  # JSON array of keywords
    intent = Column(String, nullable=True, index=True)  # Associated intent
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ConversationMemory(Base):
    """
    Conversation memory model for tracking user context.
    """
    __tablename__ = "conversation_memory"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)  # Multi-tenant support
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    last_intent = Column(String, nullable=True)
    message_count = Column(Integer, default=0, nullable=False)
    context_data = Column(Text, nullable=True)  # JSON string for additional context
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class AnalyticsEvent(Base):
    """
    Analytics event model for tracking system events.
    """
    __tablename__ = "analytics_events"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    event_type = Column(String, nullable=False, index=True)  # conversation_started, intent_detected, etc.
    event_data = Column(Text, nullable=True)  # JSON string for event details
    channel = Column(String, nullable=True, index=True)
    user_id = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class AdAsset(Base):
    """
    Ad and video creation asset model.
    """
    __tablename__ = "ad_assets"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    asset_type = Column(String, nullable=False)  # ad_copy, video, image
    title = Column(String, nullable=False)
    content = Column(Text, nullable=True)  # Ad copy text or video/image metadata
    platform = Column(String, nullable=True)  # instagram, whatsapp, facebook
    status = Column(String, default="draft", nullable=False)  # draft, published, archived
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== USERS & ROLES MODELS ==========

class Role(Base):
    """
    Role model for RBAC (Role-Based Access Control).
    """
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)  # Nullable for system roles
    name = Column(String, nullable=False, index=True)  # owner, admin, agent, viewer, custom
    description = Column(Text, nullable=True)
    is_system = Column(Boolean, default=False, nullable=False)  # System roles cannot be deleted
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Permission(Base):
    """
    Permission model for granular access control.
    """
    __tablename__ = "permissions"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, nullable=False, index=True)  # e.g., "conversations.view", "users.manage"
    description = Column(Text, nullable=True)
    category = Column(String, nullable=True, index=True)  # conversations, users, settings, etc.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class RolePermission(Base):
    """
    Many-to-many relationship between roles and permissions.
    """
    __tablename__ = "role_permissions"

    id = Column(Integer, primary_key=True, index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False, index=True)
    permission_id = Column(Integer, ForeignKey("permissions.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class UserRole(Base):
    """
    Many-to-many relationship between users and roles.
    """
    __tablename__ = "user_roles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== HANDOFF MODELS ==========

class Handoff(Base):
    """
    Handoff model for AI-to-human conversation transitions.
    """
    __tablename__ = "handoffs"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=False, index=True)
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, assigned, in_progress, resolved
    priority = Column(String, default="medium", nullable=False, index=True)  # low, medium, high, urgent
    reason = Column(Text, nullable=True)  # Why handoff was triggered
    assigned_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class SLA(Base):
    """
    SLA (Service Level Agreement) model for tracking response and resolution times.
    """
    __tablename__ = "slas"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    handoff_id = Column(Integer, ForeignKey("handoffs.id"), nullable=False, index=True)
    target_response_time = Column(Integer, nullable=True)  # Minutes
    target_resolution_time = Column(Integer, nullable=True)  # Minutes
    actual_response_time = Column(Integer, nullable=True)  # Minutes
    actual_resolution_time = Column(Integer, nullable=True)  # Minutes
    response_time_breached = Column(Boolean, default=False, nullable=False)
    resolution_time_breached = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Escalation(Base):
    """
    Escalation model for tracking conversation escalations.
    """
    __tablename__ = "escalations"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    handoff_id = Column(Integer, ForeignKey("handoffs.id"), nullable=False, index=True)
    from_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    reason = Column(Text, nullable=True)
    escalated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    resolved_at = Column(DateTime, nullable=True)


# ========== NOTIFICATIONS MODELS ==========

class Notification(Base):
    """
    Notification model for in-app notifications.
    """
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    type = Column(String, nullable=False, index=True)  # new_conversation, lead_captured, system_alert, etc.
    title = Column(String, nullable=False)
    message = Column(Text, nullable=False)
    category = Column(String, nullable=True, index=True)
    is_read = Column(Boolean, default=False, nullable=False, index=True)
    read_at = Column(DateTime, nullable=True)
    action_url = Column(String, nullable=True)  # URL to navigate when clicked
    extra_data = Column(Text, nullable=True)  # JSON string for additional data
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class NotificationPreference(Base):
    """
    Notification preference model for user notification settings.
    """
    __tablename__ = "notification_preferences"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    category = Column(String, nullable=False, index=True)  # new_conversation, lead_captured, etc.
    email_enabled = Column(Boolean, default=True, nullable=False)
    in_app_enabled = Column(Boolean, default=True, nullable=False)
    sms_enabled = Column(Boolean, default=False, nullable=False)
    quiet_hours_start = Column(String, nullable=True)  # HH:MM format
    quiet_hours_end = Column(String, nullable=True)  # HH:MM format
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== SECURITY MODELS ==========

class TwoFactorAuth(Base):
    """
    Two-Factor Authentication model.
    """
    __tablename__ = "two_factor_auth"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False, index=True)
    secret = Column(String, nullable=False)  # TOTP secret
    is_enabled = Column(Boolean, default=False, nullable=False)
    backup_codes = Column(Text, nullable=True)  # JSON array of backup codes
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class IPAllowlist(Base):
    """
    IP Allowlist model for restricting access by IP address.
    """
    __tablename__ = "ip_allowlists"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    ip_address = Column(String, nullable=False, index=True)
    description = Column(String, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)


class Session(Base):
    """
    User session model for tracking active sessions.
    """
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    session_token = Column(String, unique=True, nullable=False, index=True)
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    expires_at = Column(DateTime, nullable=False, index=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_activity = Column(DateTime, default=datetime.utcnow, nullable=False)


class APIKey(Base):
    """
    API Key model for programmatic access.
    """
    __tablename__ = "api_keys"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    key_hash = Column(String, nullable=False, unique=True, index=True)  # Hashed API key
    permissions = Column(Text, nullable=True)  # JSON array of permissions
    last_used_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True, index=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class AuditLog(Base):
    """
    Audit log model for tracking system events.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    action = Column(String, nullable=False, index=True)  # login, settings_updated, user_created, etc.
    resource_type = Column(String, nullable=True, index=True)  # user, conversation, settings, etc.
    resource_id = Column(Integer, nullable=True)
    ip_address = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    details = Column(Text, nullable=True)  # JSON string for additional details
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


# ========== SALES & PRODUCTS MODELS ==========

class Product(Base):
    """
    Product model for e-commerce.
    """
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    category = Column(String, nullable=True, index=True)
    tags = Column(Text, nullable=True)  # JSON array of tags
    image_url = Column(String, nullable=True)
    inventory_count = Column(Integer, nullable=True)  # Nullable for unlimited
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class DigitalAsset(Base):
    """
    Digital asset model for downloadable content.
    """
    __tablename__ = "digital_assets"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    file_url = Column(String, nullable=False)
    file_size = Column(Integer, nullable=True)  # Bytes
    file_type = Column(String, nullable=True)  # pdf, zip, etc.
    download_count = Column(Integer, default=0, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Service(Base):
    """
    Service model for service catalog.
    """
    __tablename__ = "services"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    duration = Column(Integer, nullable=True)  # Minutes
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Bundle(Base):
    """
    Bundle model for product/service bundles.
    """
    __tablename__ = "bundles"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    discount_percentage = Column(Float, nullable=True)
    product_ids = Column(Text, nullable=True)  # JSON array of product IDs
    service_ids = Column(Text, nullable=True)  # JSON array of service IDs
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Order(Base):
    """
    Order model for sales transactions.
    """
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=True, index=True)
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=True, index=True)
    customer_name = Column(String, nullable=True)
    customer_email = Column(String, nullable=True, index=True)
    customer_phone = Column(String, nullable=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, confirmed, shipped, delivered, cancelled
    total_amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    payment_status = Column(String, default="pending", nullable=False, index=True)  # pending, paid, refunded
    payment_method = Column(String, nullable=True)
    shipping_address = Column(Text, nullable=True)  # JSON string
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class OrderItem(Base):
    """
    Order item model for order line items.
    """
    __tablename__ = "order_items"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    service_id = Column(Integer, ForeignKey("services.id"), nullable=True)
    bundle_id = Column(Integer, ForeignKey("bundles.id"), nullable=True)
    item_type = Column(String, nullable=False)  # product, service, bundle
    name = Column(String, nullable=False)
    quantity = Column(Integer, nullable=False)
    unit_price = Column(Float, nullable=False)
    total_price = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== ONBOARDING MODELS ==========

class OnboardingStep(Base):
    """
    Onboarding step model for defining onboarding flow.
    """
    __tablename__ = "onboarding_steps"

    id = Column(Integer, primary_key=True, index=True)
    step_key = Column(String, unique=True, nullable=False, index=True)  # welcome, connect_channel, etc.
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    order = Column(Integer, nullable=False)
    is_required = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class OnboardingProgress(Base):
    """
    Onboarding progress model for tracking user onboarding.
    """
    __tablename__ = "onboarding_progress"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    step_key = Column(String, nullable=False, index=True)
    is_completed = Column(Boolean, default=False, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== CRM MODELS ==========

class Contact(Base):
    """
    Contact model for CRM - enhanced version of Lead.
    """
    __tablename__ = "contacts"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=True)
    email = Column(String, nullable=True, index=True)
    phone = Column(String, nullable=True, index=True)
    company = Column(String, nullable=True)
    job_title = Column(String, nullable=True)
    address = Column(Text, nullable=True)
    city = Column(String, nullable=True)
    country = Column(String, nullable=True)
    tags = Column(Text, nullable=True)  # JSON array
    notes = Column(Text, nullable=True)
    source = Column(String, nullable=True)  # How they found us
    status = Column(String, default="lead", nullable=False, index=True)  # lead, customer, prospect, etc.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Interaction(Base):
    """
    Interaction history for contacts (calls, emails, meetings, etc.)
    """
    __tablename__ = "interactions"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    contact_id = Column(Integer, ForeignKey("contacts.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    type = Column(String, nullable=False)  # call, email, meeting, note, etc.
    subject = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    interaction_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class PipelineStage(Base):
    """
    Sales pipeline stages (Lead → Qualified → Proposal → Closed Won/Lost)
    """
    __tablename__ = "pipeline_stages"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    order = Column(Integer, nullable=False, default=0)
    color = Column(String, nullable=True)  # For UI display
    is_default = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class PipelineOpportunity(Base):
    """
    Sales opportunities in the pipeline.
    """
    __tablename__ = "pipeline_opportunities"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    contact_id = Column(Integer, ForeignKey("contacts.id"), nullable=False, index=True)
    stage_id = Column(Integer, ForeignKey("pipeline_stages.id"), nullable=False, index=True)
    title = Column(String, nullable=False)
    value = Column(Float, nullable=True)  # Expected deal value
    currency = Column(String, default="USD", nullable=False)
    probability = Column(Integer, default=0, nullable=False)  # 0-100%
    expected_close_date = Column(DateTime, nullable=True)
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== FINANCE MODELS ==========

class Invoice(Base):
    """
    Invoice model for billing customers.
    """
    __tablename__ = "invoices"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    invoice_number = Column(String, unique=True, nullable=False, index=True)
    contact_id = Column(Integer, ForeignKey("contacts.id"), nullable=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True, index=True)
    status = Column(String, default="draft", nullable=False, index=True)  # draft, sent, paid, overdue, cancelled
    issue_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    due_date = Column(DateTime, nullable=True)
    paid_date = Column(DateTime, nullable=True)
    subtotal = Column(Float, nullable=False)
    tax_amount = Column(Float, default=0.0, nullable=False)
    discount_amount = Column(Float, default=0.0, nullable=False)
    total_amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class InvoiceItem(Base):
    """
    Invoice line items.
    """
    __tablename__ = "invoice_items"

    id = Column(Integer, primary_key=True, index=True)
    invoice_id = Column(Integer, ForeignKey("invoices.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    service_id = Column(Integer, ForeignKey("services.id"), nullable=True)
    description = Column(String, nullable=False)
    quantity = Column(Float, nullable=False, default=1.0)
    unit_price = Column(Float, nullable=False)
    tax_rate = Column(Float, default=0.0, nullable=False)
    total = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class Expense(Base):
    """
    Business expense tracking.
    """
    __tablename__ = "expenses"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    category_id = Column(Integer, ForeignKey("expense_categories.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    description = Column(String, nullable=False)
    amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    expense_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    receipt_url = Column(String, nullable=True)
    payment_method = Column(String, nullable=True)  # cash, card, bank_transfer, etc.
    vendor = Column(String, nullable=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ExpenseCategory(Base):
    """
    Expense categories for organization.
    """
    __tablename__ = "expense_categories"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    color = Column(String, nullable=True)  # For UI display
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class Payment(Base):
    """
    Payment records (for invoices, orders, etc.)
    """
    __tablename__ = "payments"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    invoice_id = Column(Integer, ForeignKey("invoices.id"), nullable=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True, index=True)
    payment_method_id = Column(Integer, ForeignKey("payment_methods.id"), nullable=True, index=True)
    amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    payment_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    reference_number = Column(String, nullable=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, completed, failed, refunded
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class PaymentMethod(Base):
    """
    Payment methods (Mobile Money, PayPal, Bank, etc.)
    """
    __tablename__ = "payment_methods"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)  # M-Pesa, PayPal, Bank Transfer, etc.
    type = Column(String, nullable=False)  # mobile_money, card, bank, digital_wallet
    is_active = Column(Boolean, default=True, nullable=False)
    credentials = Column(Text, nullable=True)  # JSON string for API keys, etc.
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class TaxRate(Base):
    """
    Tax rate configuration (VAT, Sales Tax, etc.)
    """
    __tablename__ = "tax_rates"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)  # VAT, Sales Tax, etc.
    rate = Column(Float, nullable=False)  # Percentage (e.g., 16.0 for 16%)
    is_default = Column(Boolean, default=False, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class TaxTransaction(Base):
    """
    Tax transactions for reporting.
    """
    __tablename__ = "tax_transactions"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    tax_rate_id = Column(Integer, ForeignKey("tax_rates.id"), nullable=False, index=True)
    invoice_id = Column(Integer, ForeignKey("invoices.id"), nullable=True, index=True)
    amount = Column(Float, nullable=False)
    transaction_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== INVENTORY MODELS ==========

class ProductVariant(Base):
    """
    Product variants (size, color, etc.)
    """
    __tablename__ = "product_variants"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False, index=True)
    name = Column(String, nullable=False)  # e.g., "Red - Large"
    sku = Column(String, nullable=True, index=True)
    price = Column(Float, nullable=True)  # Override product price if different
    stock_quantity = Column(Integer, default=0, nullable=False)
    low_stock_threshold = Column(Integer, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class InventoryTransaction(Base):
    """
    Inventory movement history (stock in, stock out, adjustments)
    """
    __tablename__ = "inventory_transactions"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False, index=True)
    variant_id = Column(Integer, ForeignKey("product_variants.id"), nullable=True, index=True)
    type = Column(String, nullable=False, index=True)  # stock_in, stock_out, adjustment, return
    quantity = Column(Integer, nullable=False)
    previous_quantity = Column(Integer, nullable=True)
    new_quantity = Column(Integer, nullable=False)
    reason = Column(String, nullable=True)
    reference_id = Column(Integer, nullable=True)  # Link to order, purchase order, etc.
    reference_type = Column(String, nullable=True)  # order, purchase_order, adjustment, etc.
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


# ========== PURCHASING MODELS ==========

class Supplier(Base):
    """
    Supplier/vendor management.
    """
    __tablename__ = "suppliers"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    contact_person = Column(String, nullable=True)
    email = Column(String, nullable=True, index=True)
    phone = Column(String, nullable=True)
    address = Column(Text, nullable=True)
    payment_terms = Column(String, nullable=True)  # e.g., "Net 30"
    notes = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class PurchaseOrder(Base):
    """
    Purchase orders to suppliers.
    """
    __tablename__ = "purchase_orders"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    supplier_id = Column(Integer, ForeignKey("suppliers.id"), nullable=False, index=True)
    po_number = Column(String, unique=True, nullable=False, index=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, ordered, received, paid, cancelled
    order_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    expected_delivery_date = Column(DateTime, nullable=True)
    received_date = Column(DateTime, nullable=True)
    subtotal = Column(Float, nullable=False)
    tax_amount = Column(Float, default=0.0, nullable=False)
    total_amount = Column(Float, nullable=False)
    currency = Column(String, default="USD", nullable=False)
    notes = Column(Text, nullable=True)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class PurchaseOrderItem(Base):
    """
    Purchase order line items.
    """
    __tablename__ = "purchase_order_items"

    id = Column(Integer, primary_key=True, index=True)
    purchase_order_id = Column(Integer, ForeignKey("purchase_orders.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True, index=True)
    description = Column(String, nullable=False)
    quantity = Column(Float, nullable=False)
    unit_price = Column(Float, nullable=False)
    total = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== PROJECTS & TASKS MODELS ==========

class Project(Base):
    """
    Project management.
    """
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    status = Column(String, default="planning", nullable=False, index=True)  # planning, active, on_hold, completed, cancelled
    priority = Column(String, default="medium", nullable=False, index=True)  # low, medium, high, urgent
    start_date = Column(DateTime, nullable=True)
    due_date = Column(DateTime, nullable=True)
    completed_date = Column(DateTime, nullable=True)
    progress = Column(Integer, default=0, nullable=False)  # 0-100%
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Task(Base):
    """
    Task management.
    """
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=True, index=True)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    status = Column(String, default="todo", nullable=False, index=True)  # todo, in_progress, review, done, cancelled
    priority = Column(String, default="medium", nullable=False, index=True)  # low, medium, high, urgent
    due_date = Column(DateTime, nullable=True)
    completed_date = Column(DateTime, nullable=True)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class TaskAssignment(Base):
    """
    Task assignments to users.
    """
    __tablename__ = "task_assignments"

    id = Column(Integer, primary_key=True, index=True)
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    assigned_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    assigned_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class TaskComment(Base):
    """
    Comments on tasks.
    """
    __tablename__ = "task_comments"

    id = Column(Integer, primary_key=True, index=True)
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    comment = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== MESSAGING MODELS ==========

class Channel(Base):
    """
    Internal messaging channels (teams, groups).
    """
    __tablename__ = "channels"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    is_private = Column(Boolean, default=False, nullable=False)
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ChannelMember(Base):
    """
    Channel members.
    """
    __tablename__ = "channel_members"

    id = Column(Integer, primary_key=True, index=True)
    channel_id = Column(Integer, ForeignKey("channels.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    joined_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class InternalMessage(Base):
    """
    Internal team messages.
    """
    __tablename__ = "internal_messages"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    channel_id = Column(Integer, ForeignKey("channels.id"), nullable=True, index=True)
    sender_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    recipient_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)  # For direct messages
    message = Column(Text, nullable=False)
    is_read = Column(Boolean, default=False, nullable=False)
    read_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class MessageAttachment(Base):
    """
    File attachments for internal messages.
    """
    __tablename__ = "message_attachments"

    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(Integer, ForeignKey("internal_messages.id"), nullable=False, index=True)
    file_url = Column(String, nullable=False)
    file_name = Column(String, nullable=False)
    file_size = Column(Integer, nullable=True)
    file_type = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ========== EMAIL MODELS ==========

class EmailTemplate(Base):
    """
    Email templates for automated communications.
    """
    __tablename__ = "email_templates"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    subject = Column(String, nullable=False)
    body = Column(Text, nullable=False)  # HTML or plain text
    variables = Column(Text, nullable=True)  # JSON array of available variables
    category = Column(String, nullable=True, index=True)  # invoice, reminder, welcome, etc.
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== AUTOMATION MODELS ==========

class RecurringTask(Base):
    """
    Recurring tasks and reminders.
    """
    __tablename__ = "recurring_tasks"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    frequency = Column(String, nullable=False)  # daily, weekly, monthly, yearly, custom
    frequency_value = Column(Integer, nullable=True)  # For custom frequencies
    next_run_date = Column(DateTime, nullable=False, index=True)
    last_run_date = Column(DateTime, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ScheduledJob(Base):
    """
    Scheduled jobs (reports, reminders, etc.)
    """
    __tablename__ = "scheduled_jobs"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    job_type = Column(String, nullable=False)  # report, reminder, backup, etc.
    job_name = Column(String, nullable=False)
    schedule = Column(String, nullable=False)  # cron expression or frequency
    last_run = Column(DateTime, nullable=True)
    next_run = Column(DateTime, nullable=True, index=True)
    is_active = Column(Boolean, default=True, nullable=False)
    config = Column(Text, nullable=True)  # JSON string for job configuration
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


# ========== HR & EMPLOYEE MANAGEMENT MODELS ==========

class Department(Base):
    """
    Department/Team model for organizational structure.
    """
    __tablename__ = "departments"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    manager_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    parent_department_id = Column(Integer, ForeignKey("departments.id"), nullable=True, index=True)  # For hierarchy
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Employee(Base):
    """
    Employee profile model - extends User with HR-specific information.
    """
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=True, index=True)
    employee_number = Column(String, nullable=True, unique=True, index=True)
    department_id = Column(Integer, ForeignKey("departments.id"), nullable=True, index=True)
    position = Column(String, nullable=True)  # Job title
    hire_date = Column(DateTime, nullable=True)
    termination_date = Column(DateTime, nullable=True)
    employment_type = Column(String, nullable=True)  # full_time, part_time, contract, intern
    phone = Column(String, nullable=True)
    address = Column(Text, nullable=True)
    city = Column(String, nullable=True)
    country = Column(String, nullable=True)
    date_of_birth = Column(DateTime, nullable=True)
    emergency_contact_name = Column(String, nullable=True)
    emergency_contact_phone = Column(String, nullable=True)
    salary = Column(Float, nullable=True)  # Monthly salary
    currency = Column(String, default="USD", nullable=False)
    notes = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Attendance(Base):
    """
    Employee attendance/time tracking.
    """
    __tablename__ = "attendance"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    check_in = Column(DateTime, nullable=True)
    check_out = Column(DateTime, nullable=True)
    break_duration = Column(Integer, nullable=True)  # Minutes
    total_hours = Column(Float, nullable=True)
    status = Column(String, default="present", nullable=False, index=True)  # present, absent, late, leave, holiday
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class LeaveRequest(Base):
    """
    Employee leave/vacation requests.
    """
    __tablename__ = "leave_requests"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False, index=True)
    leave_type = Column(String, nullable=False)  # vacation, sick, personal, unpaid
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    days_requested = Column(Integer, nullable=False)
    reason = Column(Text, nullable=True)
    status = Column(String, default="pending", nullable=False, index=True)  # pending, approved, rejected, cancelled
    approved_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    approved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class PerformanceReview(Base):
    """
    Employee performance reviews/evaluations.
    """
    __tablename__ = "performance_reviews"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False, index=True)
    review_period_start = Column(DateTime, nullable=False)
    review_period_end = Column(DateTime, nullable=False)
    reviewed_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    overall_rating = Column(Integer, nullable=True)  # 1-5 scale
    goals_achieved = Column(Text, nullable=True)  # JSON or text
    strengths = Column(Text, nullable=True)
    areas_for_improvement = Column(Text, nullable=True)
    comments = Column(Text, nullable=True)
    status = Column(String, default="draft", nullable=False, index=True)  # draft, completed, archived
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class EmployeeDocument(Base):
    """
    Employee documents (contracts, certificates, etc.).
    """
    __tablename__ = "employee_documents"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    employee_id = Column(Integer, ForeignKey("employees.id"), nullable=False, index=True)
    document_type = Column(String, nullable=False)  # contract, certificate, id, resume, etc.
    title = Column(String, nullable=False)
    file_url = Column(String, nullable=False)
    file_name = Column(String, nullable=False)
    file_size = Column(Integer, nullable=True)
    file_type = Column(String, nullable=True)
    expiry_date = Column(DateTime, nullable=True)
    notes = Column(Text, nullable=True)
    uploaded_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

