"""Database models using SQLAlchemy ORM.

This module contains all database models for the application.
Models inherit from Base (defined in database.py) and represent
database tables using SQLAlchemy's declarative syntax.

All models are designed for SQLite Phase 1 but can migrate to PostgreSQL
without code changes (ORM abstraction).
"""
from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Float
from sqlalchemy.orm import relationship

from app.database import Base


class Conversation(Base):
    """
    Conversation model for storing user-bot interactions.

    This model stores complete conversation records including:
    - User messages and bot replies
    - Channel/platform information
    - Detected intent
    - Timestamp for each conversation

    Table: conversations
    """

    __tablename__ = "conversations"

    # Primary key - auto-incrementing integer
    id = Column(Integer, primary_key=True, index=True)

    # User identifier - platform-specific user ID (e.g., Telegram user ID)
    # Stored as string to support different platform ID formats
    user_id = Column(String, nullable=False, index=True)

    # Channel/platform - messaging platform (telegram, whatsapp, instagram)
    # Stored as string matching MessageChannel enum values
    channel = Column(String, nullable=False, index=True)

    # User message - the original message from the user
    # Using Text type to support long messages
    user_message = Column(Text, nullable=False)

    # Bot reply - the response generated by the AI brain
    # Using Text type to support long responses
    bot_reply = Column(Text, nullable=False)

    # Intent - detected intent from the message (greeting, help, pricing, etc.)
    # Stored as string matching Intent enum values from ai_brain.py
    intent = Column(String, nullable=False, index=True)

    # Created timestamp - when the conversation was recorded
    # Automatically set to current UTC time when record is created
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class User(Base):
    """
    User model for authentication and access control.

    Supports multiple roles: Admin, Business Owner, Agent
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=True)
    role = Column(String, nullable=False, default="agent")  # admin, business_owner, agent
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Business(Base):
    """
    Business/Workspace model for multi-tenant support.
    """
    __tablename__ = "businesses"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    settings = Column(Text, nullable=True)  # JSON string for flexible settings
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ChannelIntegration(Base):
    """
    Channel integration model for managing platform connections.
    """
    __tablename__ = "channel_integrations"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)  # telegram, whatsapp, instagram, etc.
    channel_name = Column(String, nullable=True)  # Custom name for the integration
    credentials = Column(Text, nullable=True)  # Encrypted JSON credentials
    is_active = Column(Boolean, default=True, nullable=False)
    webhook_url = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class Message(Base):
    """
    Individual message model for detailed conversation tracking.
    """
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    conversation_id = Column(Integer, ForeignKey("conversations.id"), nullable=True, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    message_text = Column(Text, nullable=False)
    is_from_user = Column(Boolean, nullable=False)  # True = user message, False = bot reply
    intent = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class Lead(Base):
    """
    Lead model for capturing and tracking potential customers.
    """
    __tablename__ = "leads"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True, index=True)
    phone = Column(String, nullable=True)
    status = Column(String, default="new", nullable=False, index=True)  # new, contacted, qualified, converted
    source_intent = Column(String, nullable=True)  # Intent that triggered lead capture
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class KnowledgeEntry(Base):
    """
    Knowledge base entry model for FAQs and documents.
    """
    __tablename__ = "knowledge_entries"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    keywords = Column(Text, nullable=True)  # JSON array of keywords
    intent = Column(String, nullable=True, index=True)  # Associated intent
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class ConversationMemory(Base):
    """
    Conversation memory model for tracking user context.
    """
    __tablename__ = "conversation_memory"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, nullable=False, index=True)
    channel = Column(String, nullable=False, index=True)
    last_intent = Column(String, nullable=True)
    message_count = Column(Integer, default=0, nullable=False)
    context_data = Column(Text, nullable=True)  # JSON string for additional context
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class AnalyticsEvent(Base):
    """
    Analytics event model for tracking system events.
    """
    __tablename__ = "analytics_events"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=True, index=True)
    event_type = Column(String, nullable=False, index=True)  # conversation_started, intent_detected, etc.
    event_data = Column(Text, nullable=True)  # JSON string for event details
    channel = Column(String, nullable=True, index=True)
    user_id = Column(String, nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class AdAsset(Base):
    """
    Ad and video creation asset model.
    """
    __tablename__ = "ad_assets"

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(Integer, ForeignKey("businesses.id"), nullable=False, index=True)
    asset_type = Column(String, nullable=False)  # ad_copy, video, image
    title = Column(String, nullable=False)
    content = Column(Text, nullable=True)  # Ad copy text or video/image metadata
    platform = Column(String, nullable=True)  # instagram, whatsapp, facebook
    status = Column(String, default="draft", nullable=False)  # draft, published, archived
    extra_data = Column(Text, nullable=True)  # JSON string for additional data (renamed from metadata - SQLAlchemy reserved)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

